# Generated by Django 2.1 on 2018-08-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credits',
            unique_together={('creator', 'issue')},
        ),
    ]
