# Generated by Django 2.1.1 on 2018-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_unique_credits_enforce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvid', models.PositiveIntegerField(unique=True, verbose_name='Comic Vine ID')),
                ('cvurl', models.URLField(verbose_name='Comic Vine URL')),
                ('name', models.CharField(max_length=200, verbose_name='Arc Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=150, upload_to='images/arcs/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='arcs',
            field=models.ManyToManyField(blank=True, to='comics.Arc'),
        ),
    ]
