# Generated by Django 2.1.2 on 2018-10-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_add_story_arc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='image',
            field=models.ImageField(blank=True, max_length=150, upload_to='images/arcs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, max_length=150, upload_to='images/creators/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, max_length=150, upload_to='images/issues/%Y/%m/%d/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(blank=True, max_length=150, upload_to='images/publishers/%Y/%m/%d/'),
        ),
    ]
